# Generated by Django 3.0 on 2021-07-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FTE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('completion_time', models.DateTimeField(verbose_name='Completion Time')),
                ('rsm_email', models.EmailField(max_length=50, verbose_name='Email')),
                ('rsm_name', models.CharField(max_length=100, verbose_name='RSM Name')),
                ('head_count_date', models.DateTimeField(verbose_name='Total Headcount on')),
                ('fte', models.IntegerField(verbose_name='FTE')),
                ('total_active_selling', models.IntegerField(verbose_name='Total Active Selling')),
                ('total_sales', models.IntegerField(verbose_name='Total Sales')),
                ('group_sales_gas', models.IntegerField(blank=True, verbose_name='Group Sales GAS')),
                ('total_active_electricity', models.IntegerField(blank=True, verbose_name='Group Sales Electricity')),
                ('induction_headcount', models.IntegerField(blank=True, verbose_name='Induction')),
                ('total_headcount', models.IntegerField(verbose_name='Active Including Induction')),
                ('total_calls', models.IntegerField(verbose_name='Total Calls')),
                ('decision_makers_met_dmm', models.IntegerField(verbose_name='Decision Makers Met (DMM)')),
                ('decision_makers_presented_dmp', models.IntegerField(verbose_name='Decision Makers Presented (DMP)')),
            ],
            options={
                'verbose_name': 'FTE Form',
                'verbose_name_plural': 'FTE Forms',
            },
        ),
    ]
