# Generated by Django 3.0 on 2021-07-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgeForms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fte',
            name='completion_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completion Time'),
        ),
        migrations.AlterField(
            model_name='fte',
            name='rsm_email',
            field=models.EmailField(blank=True, max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='fte',
            name='rsm_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='RSM Name'),
        ),
        migrations.AlterField(
            model_name='fte',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Start Time'),
        ),
    ]
