# Generated by Django 3.0 on 2021-07-21 14:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_auto_20210720_1004'),
        ('bgeForms', '0003_auto_20210720_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedPaperSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mprn', models.IntegerField(validators=[django.core.validators.MinLengthValidator(11)])),
                ('gprn', models.IntegerField(validators=[django.core.validators.MinLengthValidator(7)])),
                ('sale_type', models.CharField(choices=[('ELE', 'Electricity Only'), ('NGAS', 'New Gas Customer'), ('NDUAL', 'New Dual Fuel Customer')], max_length=100)),
                ('processor_name', models.CharField(blank=True, max_length=100, verbose_name='Processor Name')),
                ('submitted_on', models.DateTimeField(auto_now_add=True, verbose_name='Submission Date')),
                ('sales_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
            options={
                'verbose_name': 'Processed Paper Sales Form',
                'verbose_name_plural': 'Processed PaperS ales Forms',
            },
        ),
    ]
