# Generated by Django 3.0 on 2021-07-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgeForms', '0004_processedpapersales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedpapersales',
            name='gprn',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='processedpapersales',
            name='mprn',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
