# Generated by Django 3.0 on 2021-07-21 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_auto_20210720_1004'),
        ('bgeForms', '0005_auto_20210721_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedpapersales',
            name='gprn',
            field=models.CharField(blank=True, max_length=1000, verbose_name='GPRN'),
        ),
        migrations.AlterField(
            model_name='processedpapersales',
            name='mprn',
            field=models.CharField(blank=True, max_length=1000, verbose_name='MPRN'),
        ),
        migrations.AlterField(
            model_name='processedpapersales',
            name='sale_type',
            field=models.CharField(choices=[('ELE', 'Electricity Only'), ('NGAS', 'New Gas Customer'), ('NDUAL', 'New Dual Fuel Customer')], max_length=100, verbose_name='Sale Type'),
        ),
        migrations.AlterField(
            model_name='processedpapersales',
            name='sales_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee', verbose_name='Agent'),
        ),
    ]
