# Generated by Django 3.0 on 2021-07-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgeForms', '0006_auto_20210721_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedpapersales',
            name='gprn',
            field=models.TextField(blank=True, max_length=1000, verbose_name='GPRN'),
        ),
        migrations.AlterField(
            model_name='processedpapersales',
            name='mprn',
            field=models.TextField(blank=True, max_length=1000, verbose_name='MPRN'),
        ),
    ]
