# Generated by Django 3.0 on 2021-07-21 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgeForms', '0008_auto_20210721_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedpapersales',
            name='gprn',
            field=models.CharField(blank=True, max_length=1000, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='GPRN'),
        ),
        migrations.AlterField(
            model_name='processedpapersales',
            name='mprn',
            field=models.CharField(blank=True, max_length=1000, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='MPRN'),
        ),
    ]
