# Generated by Django 3.0 on 2021-08-16 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgeForms', '0011_auto_20210730_0931'),
        ('bgeForms', '0011_auto_20210728_1629'),
    ]

    operations = [
    ]
