# Generated by Django 3.0 on 2021-08-18 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgeForms', '0012_merge_20210818_1000'),
        ('bgeForms', '0012_merge_20210816_1624'),
    ]

    operations = [
    ]
