# Generated by Django 3.0 on 2021-09-02 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgeForms', '0013_merge_20210818_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fte',
            name='group_sales_electricity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Group Sales Electricity'),
        ),
        migrations.AlterField(
            model_name='fte',
            name='group_sales_gas',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Group Sales GAS'),
        ),
        migrations.AlterField(
            model_name='fte',
            name='induction_headcount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Induction'),
        ),
    ]
