# Generated by Django 3.0 on 2021-04-27 11:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Account/Department')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, null=True, verbose_name='Last Name')),
                ('dob', models.DateField(max_length=8, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NA', 'Non Applicable')], max_length=20, null=True)),
                ('nationality', django_countries.fields.CountryField(max_length=2, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('county', models.CharField(choices=[('carlow', 'Carlow'), ('cavan', 'Cavan'), ('clare', 'Clare'), ('cork', 'Cork'), ('donegal', 'Donegal'), ('dublin', 'Dublin'), ('galway', 'Galway'), ('kerry', 'Kerry'), ('kildare', 'Kildare'), ('kilkenny', 'Kilkenny'), ('laois', 'Laois'), ('leitrim', 'Leitrim'), ('limerick', 'Limerick'), ('longford', 'Longford'), ('louth', 'Louth'), ('mayo', 'Mayo'), ('meath', 'Meath'), ('monaghan', 'Monaghan'), ('offaly', 'Offaly'), ('roscommon', 'Roscommon'), ('sligo', 'Sligo'), ('tipperary', 'Tipperary'), ('waterford', 'Waterford'), ('westmeath', 'Westmeath'), ('wexford', 'Wexford'), ('wicklow', 'Wicklow')], max_length=20, null=True)),
                ('personal_phone', models.CharField(max_length=16, null=True)),
                ('personal_email', models.EmailField(max_length=100, null=True)),
                ('work_phone', models.CharField(max_length=16, null=True)),
                ('work_email', models.EmailField(max_length=100, null=True)),
                ('pps_no', models.CharField(max_length=15, null=True, verbose_name='PPS Number')),
                ('employee_status', models.CharField(choices=[('MT', 'Maternity'), ('ID', 'Induction'), ('AC', 'Active'), ('LV', 'Leaver'), ('LT', 'Long Term Abscence')], default='AC', max_length=20, null=True)),
                ('role_start', models.DateField(max_length=8, null=True, verbose_name='Role Start Date')),
                ('kin_first_name', models.CharField(max_length=20, null=True, verbose_name='First Name')),
                ('kin_last_name', models.CharField(max_length=50, null=True, verbose_name='Last Name')),
                ('kin_email', models.EmailField(max_length=100, null=True, validators=[django.core.validators.EmailValidator], verbose_name='Email')),
                ('kin_phone', models.CharField(max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format '+123456789'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone')),
                ('kin_relationship', models.CharField(max_length=50, null=True, verbose_name='Relationship')),
                ('visa_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Visa Number')),
                ('visa_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Visa Type')),
                ('visa_expiry', models.DateField(blank=True, max_length=8, null=True, verbose_name='Visa Expiry Date')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.Department', verbose_name='Account/Department')),
            ],
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Role')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='SubDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_department_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sub-Department')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(max_length=8, null=True, verbose_name='Leave Start Date')),
                ('end_date', models.DateField(max_length=8, null=True, verbose_name='Leave End Date')),
                ('notes', models.TextField(blank=True, max_length=900, null=True, verbose_name='Additional Notes')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
                ('leave_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.LeaveStatus', verbose_name='Leave Type')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeJobHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_start', models.DateField(max_length=8, null=True, verbose_name='Role Start Date')),
                ('role_end', models.DateField(max_length=8, null=True, verbose_name='Role End Date')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.Department', verbose_name='Account/Department')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.JobRole')),
                ('sub_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.SubDepartment', verbose_name='Sub Department')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(max_length=8, null=True, verbose_name='Attendance Date')),
                ('hours_worked', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)])),
                ('additional_hours_worked', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)])),
                ('additional_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aditional_status', to='employee.AttendanceStatus')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status', to='employee.AttendanceStatus')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.JobRole'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sub_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.SubDepartment', verbose_name='Sub Department'),
        ),
    ]
