# Generated by Django 3.0 on 2021-05-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210505_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='eircode',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Eircode'),
        ),
    ]
