# Generated by Django 3.0 on 2021-06-03 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20210512_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['department_name'], 'verbose_name': 'Account/Department', 'verbose_name_plural': 'Accounts/Departments'},
        ),
        migrations.AlterModelOptions(
            name='subdepartment',
            options={'ordering': ['sub_department_name'], 'verbose_name': 'Sub Department', 'verbose_name_plural': 'Sub Departments'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='county',
            field=models.CharField(choices=[('other', 'Other/Abroad'), ('carlow', 'Carlow'), ('cavan', 'Cavan'), ('clare', 'Clare'), ('cork', 'Cork'), ('donegal', 'Donegal'), ('dublin', 'Dublin'), ('galway', 'Galway'), ('kerry', 'Kerry'), ('kildare', 'Kildare'), ('kilkenny', 'Kilkenny'), ('laois', 'Laois'), ('leitrim', 'Leitrim'), ('limerick', 'Limerick'), ('longford', 'Longford'), ('louth', 'Louth'), ('mayo', 'Mayo'), ('meath', 'Meath'), ('monaghan', 'Monaghan'), ('offaly', 'Offaly'), ('roscommon', 'Roscommon'), ('sligo', 'Sligo'), ('tipperary', 'Tipperary'), ('waterford', 'Waterford'), ('westmeath', 'Westmeath'), ('wexford', 'Wexford'), ('wicklow', 'Wicklow')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='kin_email',
            field=models.EmailField(blank=True, max_length=100, null=True, validators=[django.core.validators.EmailValidator], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='kin_phone',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format '+123456789'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='kin_relationship',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Relationship'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=100, null=True, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_email',
            field=models.EmailField(blank=True, max_length=100, null=True, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='employeejobhistory',
            name='role_end',
            field=models.DateField(blank=True, max_length=8, null=True, verbose_name='Role End Date'),
        ),
        migrations.AlterField(
            model_name='employeeleave',
            name='end_date',
            field=models.DateField(blank=True, max_length=8, null=True, verbose_name='Leave End Date'),
        ),
    ]
