# Generated by Django 3.0 on 2021-06-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20210614_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrole',
            name='payroll_type',
            field=models.CharField(choices=[('F', 'Fortnightly'), ('M', 'Monthly')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='modified_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
