# Generated by Django 3.0 on 2021-06-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20210617_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrole',
            name='payroll_type',
        ),
        migrations.AddField(
            model_name='employee',
            name='payroll_type',
            field=models.CharField(choices=[('F', 'Fortnightly'), ('M', 'Monthly')], max_length=20, null=True),
        ),
    ]
