# Generated by Django 3.0 on 2021-07-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_auto_20210702_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocuments',
            name='file_name',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
