# Generated by Django 3.0 on 2021-07-20 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_auto_20210712_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancestatus',
            options={'ordering': ['status_name'], 'verbose_name': 'Attendance Status', 'verbose_name_plural': 'Attendance Status'},
        ),
    ]
