# Generated by Django 3.0 on 2021-07-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_auto_20210720_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='health_care',
            field=models.BooleanField(null=True, verbose_name='Laya Health Care'),
        ),
    ]
