# Generated by Django 3.0 on 2021-07-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_employee_health_care'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pension',
            field=models.BooleanField(null=True, verbose_name='Pension'),
        ),
    ]
