# Generated by Django 3.0 on 2021-08-16 16:24

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_employee_pension'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDrivingLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_date', models.DateField(blank=True, verbose_name='License Issue Date')),
                ('expiration_date', models.DateField(blank=True, verbose_name='License Expiration Date')),
                ('origin', django_countries.fields.CountryField(max_length=2, null=True, verbose_name='License Origin')),
                ('penalty_points', models.IntegerField(verbose_name='Penalty Points')),
                ('convictions', models.TextField(blank=True, max_length=900, null=True, verbose_name='Convictions')),
                ('medical_conditions', models.TextField(blank=True, max_length=900, null=True, verbose_name='Medical Conditions')),
                ('claims', models.TextField(blank=True, max_length=900, null=True, verbose_name='Claims')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
            options={
                'verbose_name': 'Employee Driving License',
                'verbose_name_plural': 'Employees Driving License',
            },
        ),
    ]
