# Generated by Django 3.0 on 2021-08-17 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_employeedrivinglicense'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeedrivinglicense',
            options={'verbose_name': 'Employee Driving License', 'verbose_name_plural': 'Employee Driving Licenses'},
        ),
        migrations.RemoveField(
            model_name='employeedrivinglicense',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='driving_license',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.EmployeeDrivingLicense'),
        ),
    ]
