# Generated by Django 3.0 on 2021-08-17 09:50

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_auto_20210817_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='driving_license',
        ),
        migrations.AddField(
            model_name='employee',
            name='driving_license_claims',
            field=models.TextField(blank=True, max_length=900, null=True, verbose_name='Claims'),
        ),
        migrations.AddField(
            model_name='employee',
            name='driving_license_convictions',
            field=models.TextField(blank=True, max_length=900, null=True, verbose_name='Convictions'),
        ),
        migrations.AddField(
            model_name='employee',
            name='driving_license_expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='License Expiration Date'),
        ),
        migrations.AddField(
            model_name='employee',
            name='driving_license_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='License Issue Date'),
        ),
        migrations.AddField(
            model_name='employee',
            name='driving_license_medical_conditions',
            field=models.TextField(blank=True, max_length=900, null=True, verbose_name='Medical Conditions'),
        ),
        migrations.AddField(
            model_name='employee',
            name='driving_license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='driving_license_origin',
            field=django_countries.fields.CountryField(max_length=2, null=True, verbose_name='License Origin'),
        ),
        migrations.AddField(
            model_name='employee',
            name='driving_license_penalty_points',
            field=models.IntegerField(null=True, verbose_name='Penalty Points'),
        ),
        migrations.DeleteModel(
            name='EmployeeDrivingLicense',
        ),
    ]
