# Generated by Django 3.0 on 2021-08-18 10:35

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_auto_20210817_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='driving_license_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Driving License Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='driving_license_origin',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='License Origin'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='driving_license_penalty_points',
            field=models.IntegerField(blank=True, null=True, verbose_name='Penalty Points'),
        ),
    ]
