# Generated by Django 3.0 on 2021-10-12 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_auto_20210818_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeHolidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carry_over_hours', models.IntegerField(blank=True, verbose_name='Carry Over Holidays')),
                ('carry_over_expiry_date', models.DateField(blank=True, max_length=8, verbose_name='Carry Over Expiry Date')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
            options={
                'verbose_name': 'Employee Holidays',
                'verbose_name_plural': 'Employees Holidays',
            },
        ),
    ]
