# Generated by Django 3.0 on 2021-10-12 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0020_employeeholidays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeholidays',
            name='carry_over_expiry_date',
            field=models.DateField(max_length=8, verbose_name='Carry Over Expiry Date'),
        ),
        migrations.AlterField(
            model_name='employeeholidays',
            name='carry_over_hours',
            field=models.FloatField(default=0, help_text='Must be entered in hours format. Days are 7.5h', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Carry Over Hours'),
        ),
    ]
