# Generated by Django 3.0 on 2021-10-19 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0021_auto_20211012_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeholidays',
            name='carry_over_hours',
            field=models.FloatField(default=0, help_text='Must be entered in hours. Days are 7.5h', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Carry Over Hours'),
        ),
    ]
