# Generated by Django 3.0 on 2021-10-26 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0022_auto_20211019_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='jobrole',
            options={'ordering': ['role_name'], 'verbose_name': 'Job Role', 'verbose_name_plural': 'Job Roles'},
        ),
        migrations.AlterModelOptions(
            name='leavestatus',
            options={'ordering': ['status_name'], 'verbose_name': 'Leave Status', 'verbose_name_plural': 'Leave Status'},
        ),
    ]
