# Generated by Django 3.0 on 2021-11-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0023_auto_20211026_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleave',
            name='has_deduction',
            field=models.BooleanField(default=False, null=True, verbose_name='Clawback/Deductions'),
        ),
    ]
