# Generated by Django 3.0 on 2021-12-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0025_auto_20211208_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='attendance_date',
            field=models.DateField(max_length=8, null=True, verbose_name='Attendance Date'),
        ),
    ]
