# Generated by Django 3.0 on 2021-12-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0026_auto_20211208_1547'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='employeeattendance',
            constraint=models.UniqueConstraint(fields=('employee', 'attendance_date'), name='unique_employee_attendance'),
        ),
    ]
