# Generated by Django 3.0 on 2021-06-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iberForms', '0002_auto_20210623_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cecdisplay',
            name='entry_type',
            field=models.CharField(choices=[('sales', 'Sales'), ('retention', 'Retention')], max_length=50),
        ),
    ]
