# Generated by Django 3.0 on 2021-08-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('imei', models.CharField(max_length=16, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
