# Generated by Django 3.0 on 2021-08-25 13:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='brand',
            field=models.CharField(default='', max_length=255, verbose_name='Brand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phone',
            name='damaged',
            field=models.BooleanField(default=False, verbose_name='Damaged'),
        ),
        migrations.AddField(
            model_name='phone',
            name='model',
            field=models.CharField(default='', max_length=255, verbose_name='Model'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('broken', 'Broken'), ('repair', 'In for Repair'), ('transit', 'Transit')], default='', max_length=20, verbose_name='Status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phone',
            name='imei',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(14), django.core.validators.MaxLengthValidator(16)], verbose_name='IMEI'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='serial_number',
            field=models.CharField(max_length=255, unique=True, verbose_name='Serial Number'),
        ),
        migrations.CreateModel(
            name='SIM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('broken', 'Broken'), ('repair', 'In for Repair'), ('transit', 'Transit')], max_length=20, verbose_name='Status')),
                ('damaged', models.BooleanField(default=False, verbose_name='Damaged')),
                ('serial_number', models.CharField(max_length=255, unique=True, verbose_name='Serial Number')),
                ('number', models.CharField(max_length=255, verbose_name='Number')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='phone',
            name='sim',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.SIM', verbose_name='SIM'),
        ),
    ]
