# Generated by Django 3.0 on 2021-08-25 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_auto_20210825_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='location',
            field=models.CharField(choices=[('cec1', 'CEC-1'), ('cec2', 'CEC-2'), ('field', 'Field'), ('galway', 'Galway'), ('other', 'Other')], max_length=20, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='sim',
            name='location',
            field=models.CharField(choices=[('cec1', 'CEC-1'), ('cec2', 'CEC-2'), ('field', 'Field'), ('galway', 'Galway'), ('other', 'Other')], max_length=20, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='phone',
            name='damaged',
            field=models.BooleanField(null=True, verbose_name='Damaged'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sim',
            name='damaged',
            field=models.BooleanField(null=True, verbose_name='Damaged'),
        ),
    ]
