# Generated by Django 3.0 on 2021-09-02 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_auto_20210818_1035'),
        ('inventory', '0003_auto_20210825_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Employee', verbose_name='Assign to Employee'),
        ),
        migrations.AddField(
            model_name='sim',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Employee', verbose_name='Assign to Employee'),
        ),
    ]
