# Generated by Django 3.0 on 2021-09-06 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_auto_20210818_1035'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0005_auto_20210902_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='damaged',
            field=models.BooleanField(default=False, null=True, verbose_name='Damaged'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='transit',
            field=models.BooleanField(default=False, null=True, verbose_name='In Transit'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='damaged',
            field=models.BooleanField(default=False, null=True, verbose_name='Damaged'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='transit',
            field=models.BooleanField(default=False, null=True, verbose_name='In Transit'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='damaged',
            field=models.BooleanField(default=False, null=True, verbose_name='Damaged'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='transit',
            field=models.BooleanField(default=False, null=True, verbose_name='In Transit'),
        ),
        migrations.CreateModel(
            name='OtherDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('serial_number', models.CharField(max_length=255, unique=True, verbose_name='Serial Number')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('broken', 'Broken'), ('repair', 'Repair')], max_length=20, verbose_name='Status')),
                ('location', models.CharField(choices=[('cec1', 'CEC-1'), ('cec2', 'CEC-2'), ('field', 'Field'), ('galway', 'Galway'), ('other', 'Other')], max_length=20, null=True, verbose_name='Location')),
                ('damaged', models.BooleanField(default=False, null=True, verbose_name='Damaged')),
                ('transit', models.BooleanField(default=False, null=True, verbose_name='In Transit')),
                ('other_device_type', models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('mouse', 'Mouse'), ('keyboard', 'Keyboard'), ('docker', 'Docker'), ('power_bank', 'Powerbank'), ('headset', 'Headset'), ('4g_modem', '4G Modem')], max_length=255, verbose_name='Device Type')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.Employee', verbose_name='Assign to Employee')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
