# Generated by Django 3.0 on 2021-09-06 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20210906_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherdevice',
            name='other_device_type',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('mouse', 'Mouse'), ('keyboard', 'Keyboard'), ('docker', 'Docker'), ('power_bank', 'Powerbank'), ('headset', 'Headset'), ('4g_modem', '4G Modem'), ('other', 'Other')], max_length=255, verbose_name='Device Type'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='sim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.SIM', unique=True, verbose_name='SIM'),
        ),
    ]
