# Generated by Django 3.0 on 2021-09-27 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20210906_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherdevice',
            name='workstation',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Workstation'),
        ),
        migrations.AddField(
            model_name='phone',
            name='workstation',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Workstation'),
        ),
        migrations.AddField(
            model_name='sim',
            name='workstation',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Workstation'),
        ),
        migrations.AddField(
            model_name='tablet',
            name='workstation',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Workstation'),
        ),
    ]
