# Generated by Django 3.0 on 2021-09-27 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20210927_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='workstation',
        ),
        migrations.RemoveField(
            model_name='sim',
            name='workstation',
        ),
        migrations.RemoveField(
            model_name='tablet',
            name='workstation',
        ),
    ]
