# Generated by Django 3.0 on 2021-10-01 09:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20210927_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherdevice',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('out_of_order', 'Out of Order'), ('repair', 'Repair')], max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='otherdevice',
            name='workstation',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Workstation Number'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('out_of_order', 'Out of Order'), ('repair', 'Repair')], max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('out_of_order', 'Out of Order'), ('repair', 'Repair')], max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='sim',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.SIM', verbose_name='SIM'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('out_of_order', 'Out of Order'), ('repair', 'Repair')], max_length=20, verbose_name='Status'),
        ),
    ]
