# Generated by Django 3.0 on 2021-10-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20211001_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherdevice',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sim',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tablet',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
