# Generated by Django 3.0 on 2021-10-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20211019_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherdevice',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True, verbose_name='Acquisition Date'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True, verbose_name='Acquisition Date'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True, verbose_name='Acquisition Date'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True, verbose_name='Acquisition Date'),
        ),
    ]
