# Generated by Django 3.0 on 2021-06-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinergyForms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cecdisplay',
            name='entry_type',
            field=models.CharField(choices=[('salesB2B', 'Sales B2B'), ('salesB2C', 'Sales B2C'), ('retention', 'Retention')], max_length=50),
        ),
    ]
