# Generated by Django 3.0 on 2021-06-24 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CECDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('entry_type', models.CharField(choices=[('sales', 'Sales'), ('retention', 'Retention')], max_length=50)),
                ('current', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('target', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
