# Generated by Django 3.0 on 2021-05-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRoles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroles',
            name='is_manager',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=10, null=True),
        ),
    ]
